### ISSUE TITLE
Assigning string values to Enums breaks compilation

### ISSUE THREAD

**Issue by kribblo** [railsware/upterm#1111]
Looks like this commit broke compilation when adding String values to enums: https://github.com/railsware/upterm/commit/2d35f09275eb38f3ee6476e3ab46d5315c6c0815

Or if this is allowed in some version of typescript or with some flag, then that's not the one I get when I do `npm install` - I don't know typescript well enough. Please advice. :)

```
$ npm run pack

> upterm@0.2.158 pack /home/kristoffer/Workspace/upterm
> npm run compile && build

npm WARN invalid config loglevel="notice"

> upterm@0.2.158 compile /home/kristoffer/Workspace/upterm
> npm run cleanup && npm run tsc && npm run copy-html


> upterm@0.2.158 cleanup /home/kristoffer/Workspace/upterm
> rimraf compiled/src


> upterm@0.2.158 tsc /home/kristoffer/Workspace/upterm
> tsc

src/Enums.ts(72,18): error TS2322: Type '"in-progress"' is not assignable to type 'Status'.
src/Enums.ts(73,15): error TS2322: Type '"failure"' is not assignable to type 'Status'.
src/Enums.ts(74,19): error TS2322: Type '"interrupted"' is not assignable to type 'Status'.
src/Enums.ts(75,15): error TS2322: Type '"success"' is not assignable to type 'Status'.
src/Enums.ts(95,12): error TS2322: Type '"info"' is not assignable to type 'LogLevel'.
src/Enums.ts(96,11): error TS2322: Type '"log"' is not assignable to type 'LogLevel'.
src/Enums.ts(97,13): error TS2322: Type '"error"' is not assignable to type 'LogLevel'.
```

**Comment by vlad-shatskyi** [comment]
You need to compile with typescript 2.4. `npm install` should help.
